### ISSUE TITLE
Curseforge: AdiBags Listed as Requirement

### ISSUE THREAD

**Issue by NHDriver4** [bhoward13/BetterBags-CraftingKnowledge#1]
AdiBags still listed as requirement on Curseforge. This is causing initial install and updates to download adibags with Curseforge client. Probably want to replace that with BetterBags. Thanks for your work!

![image](https://github.com/user-attachments/assets/4a5ff1c2-8d32-4da1-a887-22e630c30596)

**Comment by bhoward13** [comment]
Updated Curseforge Dependencies, just waiting for it to update on their end.

**Comment by bhoward13** [comment]
Dependencies updated, closing issue
